cloudProjectId: ""
dxp:
    domains: []
    mainDomain: ""
    protocol: https
enabled: true
environmentId: ""
extensions: []
main:
    namespace: ""
    serviceAccountName: liferay-default
    waitForLiferay:
        enabled: true
        endpoint: /c/portal/robots
        image:
            pullPolicy: IfNotPresent
            repository: docker.io/busybox
            tag: "1.36"
        pollIntervalSeconds: 5
overlay:
    autoRestart:
        enabled: false
    bucket: ""
    version: master
projectId: ""
rbac:
    enabled: false
    grantLiferayAccess: true
    rules: []
resourceQuota:
    enabled: false
    limits:
        cpu: "20"
        memory: 40Gi
    requests:
        cpu: "10"
        memory: 20Gi
serviceAccount:
    annotations: {}
    create: true
    gcpServiceAccount: ""
    name: ""