{{- if and .Values.enabled .Values.rbac.enabled .Values.rbac.rules -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        {{- include "sharedLabels" . | nindent 8 }}
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ .Release.Name }}
subjects:
    -   kind: ServiceAccount
        name: {{ include "serviceAccountName" . }}
        namespace: {{ .Release.Namespace }}
{{- end -}}