{{- if and .Values.enabled .Values.rbac.enabled (or .Values.rbac.rules .Values.rbac.grantLiferayAccess) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    labels:
        {{- include "sharedLabels" . | nindent 8 }}
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
rules:
    {{- if .Values.rbac.grantLiferayAccess }}
    -   apiGroups: [""]
        resources: [configmaps]
        verbs: [create, get, list, patch, update, watch]
    {{- end }}
    {{- with .Values.rbac.rules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}