{{- if and .Values.enabled .Values.rbac.enabled (or .Values.rbac.rules .Values.rbac.grantLiferayAccess) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        {{- include "sharedLabels" . | nindent 8 }}
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ .Release.Name }}
subjects:
    -   kind: ServiceAccount
        name: {{ include "serviceAccountName" . }}
        namespace: {{ .Release.Namespace }}
    {{- if .Values.rbac.grantLiferayAccess }}
    -   kind: ServiceAccount
        name: {{ required "main.serviceAccountName is required when rbac.grantLiferayAccess is true" .Values.main.serviceAccountName }}
        namespace: {{ required "main.namespace is required when rbac.grantLiferayAccess is true" .Values.main.namespace }}
    {{- end }}
{{- end -}}