{{- if .Values.enabled -}}
{{- range $ext := .Values.extensions }}
{{- if eq (dig "kind" "Deployment" $ext) "Deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        {{- include "extLabels" (dict "root" $ "ext" $ext) | nindent 8 }}
    name: {{ $ext.name }}
    namespace: {{ $.Release.Namespace }}
spec:
    replicas: {{ dig "replicaCount" 1 $ext }}
    selector:
        matchLabels:
            {{- include "extSelectorLabels" (dict "root" $ "ext" $ext) | nindent 12 }}
    template:
        {{- include "podTemplate" (dict "root" $ "ext" $ext) | nindent 8 }}
{{- end }}
{{- end }}
{{- end -}}