apiVersion: v1
kind: ServiceAccount
metadata:
  name: aihub-crawler-dispatcher
  namespace: aihub-poc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aihub-crawler-dispatcher
  namespace: aihub-poc
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aihub-crawler-dispatcher
  namespace: aihub-poc
subjects:
  - kind: ServiceAccount
    name: aihub-crawler-dispatcher
    namespace: aihub-poc
roleRef:
  kind: Role
  name: aihub-crawler-dispatcher
  apiGroup: rbac.authorization.k8s.io
