apiVersion: v1
data:
    helpers.sh: |
{{ .Files.Get "scripts/helpers.sh" | nindent 8 }}
    overlay-sync.sh: |
{{ .Files.Get "scripts/overlay-sync.sh" | nindent 8 }}
    wait-for-liferay.sh: |
{{ .Files.Get "scripts/wait-for-liferay.sh" | nindent 8 }}
kind: ConfigMap
metadata:
    labels:
        {{- include "sharedLabels" . | nindent 8 }}
    name: client-extension-init-scripts
    namespace: {{ .Release.Namespace }}