{{- if .Values.enabled -}}
apiVersion: v1
data:
    com.liferay.lxc.dxp.domains: {{ join "\n" .Values.dxp.domains | quote }}
    com.liferay.lxc.dxp.main.domain: {{ .Values.dxp.mainDomain | quote }}
    com.liferay.lxc.dxp.mainDomain: {{ .Values.dxp.mainDomain | quote }}
    com.liferay.lxc.dxp.server.protocol: {{ .Values.dxp.protocol | quote }}
kind: ConfigMap
metadata:
    labels:
        dxp.lxc.liferay.com/virtualInstanceId: {{ .Values.dxp.mainDomain | quote }}
        lxc.liferay.com/metadataType: dxp
        {{- include "sharedLabels" . | nindent 8 }}
    name: {{ printf "%s-dxp-metadata" .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
