{{- if .Values.enabled -}}
{{- range $ext := .Values.extensions }}
---
apiVersion: v1
data:
    {{- range $k, $v := (dig "runtimeEnv" dict $ext) }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
kind: ConfigMap
metadata:
    labels:
        {{- include "extLabels" (dict "root" $ "ext" $ext) | nindent 8 }}
    name: {{ printf "%s-runtime-env" $ext.name }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end -}}