{{- $search := .Values.search.elasticsearch -}}
{{- if and .Values.enabled $search.enabled }}
apiVersion: v1
kind: Namespace
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-25"
    labels:
        name: {{ include "search.namespace" . }}
        pod-security.kubernetes.io/enforce: restricted
    name: {{ include "search.namespace" . }}
{{- end -}}