{{- $search := .Values.search.elasticsearch -}}
{{- if and .Values.enabled $search.enabled $search.exporter.enabled -}}
{{- $exp := $search.exporter -}}
{{- $esName := include "search.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app.kubernetes.io/component: metrics
        app.kubernetes.io/name: elasticsearch-exporter
        projectId: {{ .Values.projectId }}
    name: {{ printf "%s-exporter" $esName }}
    namespace: {{ include "search.namespace" . }}
spec:
    replicas: {{ $exp.replicaCount }}
    selector:
        matchLabels:
            app.kubernetes.io/name: elasticsearch-exporter
    template:
        metadata:
            labels:
                app.kubernetes.io/component: metrics
                app.kubernetes.io/name: elasticsearch-exporter
                projectId: {{ .Values.projectId }}
        spec:
            automountServiceAccountToken: false
            containers:
                -   args:
                        -   --es.uri=http://{{ $esName }}-es-http:9200
                        -   --es.all
                        -   --es.indices
                        -   --es.indices_settings
                        -   --es.shards
                        -   --collector.clustersettings
                        -   --collector.snapshots
                        -   --collector.slm
                        -   --es.timeout=20s
                        -   --web.listen-address=:9114
                        -   --web.telemetry-path=/metrics
                        -   --log.format=json
                    env:
                        -   name: ES_USERNAME
                            value: elastic
                        -   name: ES_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    key: elastic
                                    name: {{ $esName }}-es-elastic-user
                    image: {{ printf "%s:%s" $exp.image.repository ($exp.image.tag | toString) }}
                    imagePullPolicy: {{ $exp.image.pullPolicy }}
                    livenessProbe:
                        {{- toYaml $exp.livenessProbe | nindent 24 }}
                    name: exporter
                    ports:
                        {{- toYaml $exp.ports | nindent 24 }}
                    readinessProbe:
                        {{- toYaml $exp.readinessProbe | nindent 24 }}
                    resources:
                        {{- toYaml $exp.resources | nindent 24 }}
                    securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                            drop:
                                -   ALL
                        readOnlyRootFilesystem: true
            securityContext:
                fsGroup: 65534
                runAsGroup: 65534
                runAsNonRoot: true
                runAsUser: 65534
                seccompProfile:
                    type: RuntimeDefault
{{- end -}}